### ISSUE TITLE
youtube-dl outputs warning about .cache folder not being writable

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [wernight/docker-youtube-dl#4]
I just checked the log-output and found this log-line in every youtube-dl call:

`WARNING: Writing cache to u'/.cache/youtube-dl/youtube-sigfuncs/js_vflpGF_3J_40.43.json' failed: Traceback (most recent call last):`

Can we ignore this or should we mount some writable location to /.cache ?

**Comment by wernight** [comment]
I'd say:

 - Should make it writable inside the container.
 - Could suggest to optionally mount that directory to preserve the cache.

**Comment by wernight** [comment]
How did you get that warning to display?

**Comment by 0xFEEDC0DE64** [comment]
I don't have the exact command anymore, but it was a youtube MP3 download. Aren't you getting the same warnings?

**Comment by wernight** [comment]
No actually I tried with some video and didn't get any.

**Comment by 0xFEEDC0DE64** [comment]
ok then let's close this issue. I will comment back if I ever download a video again and see the warnings.

**Comment by polettix** [comment]
It does not happen with all videos. The following one has the problem if you're interested: https://youtu.be/68Vp411M0zo - it seems otherwise to have no real consequence.
